project_name: verdledger
builds:
  - id: cli
    main: ./go/cmd/verdledger
    binary: verdledger
    goos:   [linux, darwin, windows]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w
dockers:
  - image_templates:
      - ghcr.io/verdledger/verdledger:{{ .Tag }}
      - ghcr.io/verdledger/verdledger:latest
    build_flag_templates:
      - --build-arg=VERSION={{ .Version }}
    dockerfile: Dockerfile
checksum: { name_template: checksums.txt }
sbom:     [ { artifact: binary } ]
