project_name: verdledger
release:
  github:
    draft: false
    prerelease: false

builds:
  - id: cli
    main: ./cmd/cli
    binary: verdledger
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
    ldflags: -s -w
  - id: api
    main: ./cmd/server
    binary: verdledger-api
    goos: [linux]
    goarch: [amd64, arm64]
  - id: advisor-action
    main: ./cmd/advisor-action
    binary: verdledger-action
    goos: [linux]
    goarch: [amd64]

archives:
  - id: default
    builds: [cli]
    format_overrides:
      - goos: windows
        format: zip

brews:
  - tap:
      owner: verdledger
      name: homebrew-verdledger
    folder: Formula
    description: "VerdLedger CLI – carbon+cost tooling"
    install: |
      bin.install "verdledger"

dockers:
  - image_templates:
      - ghcr.io/{{ .Repo.Owner }}/verdledger-api:{{ .Version }}
    builds: [api]
    use: buildx
  - image_templates:
      - ghcr.io/{{ .Repo.Owner }}/verdledger-action:{{ .Version }}
    builds: [advisor-action]
    use: buildx

checksum:
  name_template: 'checksums.txt'
