version: "3.9"
services:
  db:
    image: supabase/postgres:15
    ports: ["54322:5432"]
    environment:
      POSTGRES_PASSWORD: postgres
  audit:
    build: ./plugins/audit
    ports: ["8081:8080"]
