version: "3.9"
services:
  db:
    image: postgres:15-alpine
    ports: ["65432:5432"]
    environment:
      POSTGRES_PASSWORD: postgres

  api:
    build: ./cmd/server           # build locally
    environment:
      PUBLIC_MODE: "true"
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres?sslmode=disable
    ports: ["8080:8080"]
    depends_on: [db]

  # api:
  #   image: ghcr.io/verdledger/verdledger-api:latest
  #   depends_on: [db]
  #   environment:
  #     DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
  #     VDL_PUBLIC_MODE: "true"     # ← add this line

  #   ports: ["8080:8080"]

  optimizer:
    image: ghcr.io/verdledger/verdledger-optimizer:latest
    depends_on: [api]

  audit:
    image: ghcr.io/verdledger/verdledger-audit:latest
    depends_on: [api]

  advisor:
    image: ghcr.io/verdledger/verdledger-advisor:latest
    depends_on: [api]
