// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package ledger

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type ActivityLog struct {
	ID      uuid.UUID             `json:"id"`
	Repo    uuid.UUID             `json:"repo"`
	Ts      time.Time             `json:"ts"`
	ActorID uuid.NullUUID         `json:"actor_id"`
	Action  sql.NullString        `json:"action"`
	Meta    pqtype.NullRawMessage `json:"meta"`
}

type ApiKey struct {
	ID        uuid.UUID      `json:"id"`
	OrgID     sql.NullInt64  `json:"org_id"`
	Secret    string         `json:"secret"`
	Label     sql.NullString `json:"label"`
	CreatedAt time.Time      `json:"created_at"`
}

type Org struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

type SavingsEvent struct {
        ID     uuid.UUID      `json:"id"`
        OrgID  sql.NullInt64  `json:"org_id"`
        ProjectID sql.NullInt64 `json:"project_id"`
        Ts     time.Time      `json:"ts"`
        Cloud  sql.NullString `json:"cloud"`
        Region sql.NullString `json:"region"`
        Sku    sql.NullString `json:"sku"`
        Kwh    sql.NullString `json:"kwh"`
        Usd    sql.NullString `json:"usd"`
        Kg     sql.NullString `json:"kg"`
        Note   sql.NullString `json:"note"`
}

type Project struct {
        ID        int64     `json:"id"`
        OrgID     int64     `json:"org_id"`
        Name      string    `json:"name"`
        CreatedAt time.Time `json:"created_at"`
}

type SkuCatalogue struct {
	Cloud   string         `json:"cloud"`
	Region  string         `json:"region"`
	Sku     string         `json:"sku"`
	Watts   sql.NullString `json:"watts"`
	UsdHour sql.NullString `json:"usd_hour"`
}

type VActiveRepoWeek struct {
	ActiveRepos int64 `json:"active_repos"`
}

type VOrgWeekly struct {
	OrgID sql.NullInt64 `json:"org_id"`
	Usd   int64         `json:"usd"`
	Kg    int64         `json:"kg"`
}
