// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: placeholder.sql

package ledger

import (
	"context"
)

const health = `-- name: Health :one
SELECT 1::int AS ok
`

// A throw-away query so sqlc has something to compile
func (q *Queries) Health(ctx context.Context) (int32, error) {
	row := q.db.QueryRowContext(ctx, health)
	var ok int32
	err := row.Scan(&ok)
	return ok, err
}
