// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: projects.sql

package ledger

import (
	"context"
	"database/sql"
)

const createProject = `-- name: CreateProject :one
INSERT INTO public.project (org_id, name)
VALUES ($1, $2)
RETURNING id, org_id, name, created_at
`

type CreateProjectParams struct {
	OrgID sql.NullInt64 `json:"org_id"`
	Name  string        `json:"name"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, createProject, arg.OrgID, arg.Name)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}
