package ledger

import (
    "context"
    "time"

    "github.com/jackc/pgx/v5/pgxpool"
)

var DB *pgxpool.Pool
var Q  *Queries // generated by sqlc

// Connect initialises the global pgx pool + sqlc Queries.
func Connect(ctx context.Context, dsn string) error {
    cfg, err := pgxpool.ParseConfig(dsn)
    if err != nil {
        return err
    }
    // 15-second sane default
    cfg.MaxConnIdleTime = 15 * time.Second

    DB, err = pgxpool.NewWithConfig(ctx, cfg)
    if err != nil {
        return err
    }
    Q = New(DB)
    return nil
}
