name: Build & Push Docker images

on:
  push:
    paths:
      - 'cmd/server/**'
      - 'plugins/**'
      - 'cmd/advisor-action/**'
      - '.github/workflows/docker-build.yml'

permissions:
  contents: read
  packages: write

jobs:
  matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - context: ./cmd/server
            image: verdledger-api
          - context: ./plugins/optimizer
            image: verdledger-optimizer
          - context: ./plugins/audit
            image: verdledger-audit
          - context: ./plugins/advisor
            image: verdledger-advisor
          - context: ./cmd/advisor-action
            image: verdledger-action
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & push ${{ matrix.image }}
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.context }}
          tags: ghcr.io/${{ github.repository_owner }}/${{ matrix.image }}:latest
          push: true
