name: nightly-data-sync
on:
  schedule:
    - cron: '0 1 * * *'
jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
      - run: pnpm install --frozen-lockfile
      - run: node scripts/refresh-data.ts
      - uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore: nightly price + grid refresh"
          branch: chore/nightly-data
          title: "Nightly data sync"
          delete-branch: true
